#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/usr/local/lib/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/steffenlinssen/Library/Mobile Documents/com~apple~CloudDocs/Projekte/ringring/app"
export "FLUTTER_TARGET=/Users/steffenlinssen/Library/Mobile Documents/com~apple~CloudDocs/Projekte/ringring/app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "EXTRA_FRONT_END_OPTIONS=--no-sound-null-safety"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/steffenlinssen/Library/Mobile Documents/com~apple~CloudDocs/Projekte/ringring/app/.dart_tool/package_config.json"
